namespace:
  name: dev
  labels:
    environment: development

application:
  name: nginx-alpine

numberOfReplicas: 3

image:
  repository: nginx
  tag: latest

resources:
  cpu: "50m"
  memory: "256Mi"

service:
  port: 8111